/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import threads.OutputThread;

/**
 *
 * @author Phat
 */
public class ChatPanel extends javax.swing.JPanel {
    Socket socket;
    DataOutputStream os;
    BufferedReader br;
    String sender;
    String receiver;
    
    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
    }

    public JTextArea getLogsTxt() {
        return logTxt;
    }
    
    public ChatPanel(Socket socket, String sender, String receiver) {
        try {
            this.socket = socket;
            this.sender = sender;
            this.receiver = receiver;
            os = new DataOutputStream(socket.getOutputStream());
            br = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            initComponents();
        } catch (IOException ex) {
            Logger.getLogger(ChatPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logTxt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatTxt = new javax.swing.JTextArea();
        sendBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        logTxt.setEditable(false);
        logTxt.setColumns(20);
        logTxt.setRows(5);
        logTxt.setBorder(null);
        jScrollPane1.setViewportView(logTxt);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Message"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        chatTxt.setColumns(20);
        chatTxt.setRows(5);
        jScrollPane2.setViewportView(chatTxt);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        sendBtn.setBackground(new java.awt.Color(0, 153, 153));
        sendBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendBtn.setText("Send");
        sendBtn.setPreferredSize(new java.awt.Dimension(57, 30));
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sendBtn, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        if (chatTxt.getText().trim().equals("")) return;
        try {
            logTxt.append(sender + ": " + chatTxt.getText() + "\n");
            logTxt.updateUI();
            os.writeBytes(chatTxt.getText());
            os.write(13);
            os.write(10);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error sending message " + chatTxt.getText());
        }
    }//GEN-LAST:event_sendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logTxt;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
