package view.panel;


import controller.Logs;
import model.users.UserDTO;
import model.users.UserDAO;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import controller.ImageLoader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nguyenhongphat0
 */
public class AccountPanel extends javax.swing.JPanel {
    UserDTO user;
    String avatarLink;
    JLabel logoLabel;

    /**
     * Creates new form AccountPanel
     */
    public AccountPanel(UserDTO user, JLabel logoLabel) {
        initComponents();
        this.user = user;
        this.logoLabel = logoLabel;
        yourroleisLbl.setText("You role is " + user.roles);
        loadLogs();
    }
    
    public void loadLogs() {
        Logs.pop(user.username, logsLbl);
    }

    public UserDTO retriveUserInfo() {
        String username = usernameTxt.getText();
        String password = new String(passwordTxt.getPassword());
        String fullname = fullnameTxt.getText();
        String role = user.roles;
        String passhint = passhintTxt.getText();
        String avatar = avatarLink;
        return new UserDTO(username, password, fullname, role, passhint, avatar);
    }
    
    public void distriveUserInfo() {
        String[] names = user.fullname.split(" ");
        titleLbl.setText(names[names.length-1] + "'s profile");
        usernameTxt.setText(user.username);
        passwordTxt.setText(user.password);
        fullnameTxt.setText(user.fullname);
        passhintTxt.setText(user.passhint);
        avatarLink = user.avatar;
        ImageLoader.smartAttaching(avatarLink, avatarLbl);
        ImageLoader.smartAttaching(avatarLink, logoLabel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        showPasswordBtn = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        avatarLbl = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        changeAvatarBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        passhintTxt = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        yourroleisLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logsLbl = new javax.swing.JLabel();
        fullnameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 254, 247));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel1.setText("Username");

        usernameTxt.setEditable(false);
        usernameTxt.setPreferredSize(new java.awt.Dimension(16, 40));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel2.setText("Password");

        showPasswordBtn.setBackground(new java.awt.Color(203, 203, 203));
        showPasswordBtn.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        showPasswordBtn.setForeground(new java.awt.Color(1, 1, 1));
        showPasswordBtn.setText("show password");
        showPasswordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel3.setText("Avatar");

        updateBtn.setBackground(new java.awt.Color(189, 0, 0));
        updateBtn.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.setMargin(new java.awt.Insets(5, 15, 5, 15));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(203, 203, 203));
        cancelBtn.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(1, 1, 1));
        cancelBtn.setText("Cancel");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.setMargin(new java.awt.Insets(5, 15, 5, 15));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        passwordTxt.setEchoChar('@');
        passwordTxt.setPreferredSize(new java.awt.Dimension(16, 40));

        changeAvatarBtn.setBackground(new java.awt.Color(203, 203, 203));
        changeAvatarBtn.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        changeAvatarBtn.setForeground(new java.awt.Color(1, 1, 1));
        changeAvatarBtn.setText("change avatar");
        changeAvatarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeAvatarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAvatarBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel4.setText("Password Hint");

        passhintTxt.setPreferredSize(new java.awt.Dimension(16, 40));

        titleLbl.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        titleLbl.setText("Phatias account");

        jLabel7.setBackground(new java.awt.Color(1, 1, 1));
        jLabel7.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(245, 254, 247));

        yourroleisLbl.setText("Your roles is ADMIN");

        jLabel8.setFont(new java.awt.Font("Cantarell", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(132, 132, 132));
        jLabel8.setText("Recent activities");

        logsLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yourroleisLbl)
                    .addComponent(jLabel8))
                .addContainerGap(354, Short.MAX_VALUE))
            .addComponent(logsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yourroleisLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fullnameTxt.setPreferredSize(new java.awt.Dimension(16, 40));

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel9.setText("Fullname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passhintTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(279, 279, 279))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avatarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(showPasswordBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(changeAvatarBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fullnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLbl)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(fullnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPasswordBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(passhintTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(avatarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeAvatarBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cancelBtn)
                                    .addComponent(updateBtn))))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        UserDTO newUser = retriveUserInfo();
        newUser.avatar = "asset/users/" + newUser.username + ".jpg";
        ImageLoader.copyImage(avatarLink, newUser.avatar);
        if (UserDAO.updateUser(newUser)) {
            this.user = newUser;
            distriveUserInfo();
            Logs.push(user.username, "update profile information to:");
            Logs.push("[" + user.username + "]" + newUser.toString());
            JOptionPane.showMessageDialog(null, "Update profile information successfully");
        }
        else JOptionPane.showMessageDialog(null, "Error updating information");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void changeAvatarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAvatarBtnActionPerformed
        // TODO add your handling code here
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showDialog(this, "Load an image") == JFileChooser.APPROVE_OPTION) {
            avatarLink = fileChooser.getSelectedFile().getPath();
            ImageLoader.smartAttaching(avatarLink, avatarLbl);
        }
    }//GEN-LAST:event_changeAvatarBtnActionPerformed

    private void showPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordBtnActionPerformed
        // TODO add your handling code here:
        if (showPasswordBtn.isSelected()) {
            passwordTxt.setEchoChar('\0');
        } else {
            passwordTxt.setEchoChar('@');
        }
    }//GEN-LAST:event_showPasswordBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        distriveUserInfo();
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarLbl;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changeAvatarBtn;
    private javax.swing.JTextField fullnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logsLbl;
    private javax.swing.JTextField passhintTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JToggleButton showPasswordBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JLabel yourroleisLbl;
    // End of variables declaration//GEN-END:variables
}
