package view.panel;


import controller.Logs;
import model.phones.PhoneDAO;
import model.phones.PhoneDTO;
import model.users.UserDTO;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.ImageLoader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nguyenhongphat0
 */
public class UserPhonePanel extends javax.swing.JPanel {
    DefaultTableModel model;
    String pictureLink = null;
    UserDTO currentUser;
    
    /**
     * Creates new form PhonesPanel
     */
    public UserPhonePanel(UserDTO user) {
        initComponents();
        this.currentUser = user;
        model = getTableModel();
        phoneTable.setFillsViewportHeight(true);
        ArrayList<PhoneDTO> list = PhoneDAO.getAllPhones();
        showPhones(list);
    }
    
    public void showPhones(ArrayList<PhoneDTO> phones) {
        model.setRowCount(0);
        phones.forEach((phone) -> {
            model.addRow(phone.toVector());
        });
    }
    
    private DefaultTableModel getTableModel() {
        return (DefaultTableModel) phoneTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        searchTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        detailPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        osTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        descriptionTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        phoneTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        detailImg = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        searchTxt.setBackground(new java.awt.Color(12, 12, 12));
        searchTxt.setForeground(new java.awt.Color(255, 255, 255));
        searchTxt.setText("search something...");
        searchTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 12, 12), 5));
        searchTxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        searchTxt.setPreferredSize(new java.awt.Dimension(137, 40));
        searchTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTxtFocusLost(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtKeyPressed(evt);
            }
        });
        jPanel1.add(searchTxt, java.awt.BorderLayout.PAGE_START);

        jPanel6.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jPanel6.setLayout(new java.awt.BorderLayout());

        detailPanel.setBackground(new java.awt.Color(245, 254, 247));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 9)); // NOI18N
        jLabel1.setText("ID: ");

        idTxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        idTxt.setMinimumSize(new java.awt.Dimension(0, 33));
        idTxt.setPreferredSize(new java.awt.Dimension(16, 35));

        nameTxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        nameTxt.setMinimumSize(new java.awt.Dimension(0, 33));
        nameTxt.setPreferredSize(new java.awt.Dimension(16, 35));

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 9)); // NOI18N
        jLabel2.setText("Name:");

        osTxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        osTxt.setMinimumSize(new java.awt.Dimension(0, 33));
        osTxt.setPreferredSize(new java.awt.Dimension(16, 35));

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 9)); // NOI18N
        jLabel3.setText("OS:");

        priceTxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        priceTxt.setMinimumSize(new java.awt.Dimension(0, 33));
        priceTxt.setPreferredSize(new java.awt.Dimension(16, 35));

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 9)); // NOI18N
        jLabel4.setText("Price:");

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 9)); // NOI18N
        jLabel5.setText("Description: ");

        descriptionTxt.setMargin(new java.awt.Insets(0, 10, 0, 0));
        descriptionTxt.setMinimumSize(new java.awt.Dimension(0, 33));
        descriptionTxt.setPreferredSize(new java.awt.Dimension(16, 35));

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priceTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailPanelLayout.createSequentialGroup()
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 407, Short.MAX_VALUE))
                    .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(osTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(osTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jPanel6.add(detailPanel, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(245, 254, 247));

        jPanel7.setBackground(new java.awt.Color(245, 254, 247));
        jPanel7.setLayout(new java.awt.CardLayout());

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(250, 32767));

        phoneTable.setBackground(new java.awt.Color(254, 255, 255));
        phoneTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        phoneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Pice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        phoneTable.setGridColor(new java.awt.Color(254, 254, 254));
        phoneTable.setMaximumSize(new java.awt.Dimension(255, 0));
        phoneTable.setRowHeight(30);
        phoneTable.setRowMargin(0);
        phoneTable.setSelectionBackground(new java.awt.Color(188, 36, 26));
        phoneTable.setSelectionForeground(new java.awt.Color(240, 240, 240));
        phoneTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        phoneTable.setShowVerticalLines(false);
        phoneTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneTableMouseClicked(evt);
            }
        });
        phoneTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(phoneTable);
        if (phoneTable.getColumnModel().getColumnCount() > 0) {
            phoneTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            phoneTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            phoneTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        jPanel7.add(jScrollPane1, "card2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(245, 254, 247));
        jPanel3.setLayout(new java.awt.BorderLayout());

        controlPanel.setBackground(new java.awt.Color(245, 254, 247));

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jPanel3.add(controlPanel, java.awt.BorderLayout.PAGE_END);

        detailImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(detailImg, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel1, "card3");

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTxtFocusGained
        // TODO add your handling code here:
        searchTxt.setText("");
    }//GEN-LAST:event_searchTxtFocusGained

    private void searchTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTxtFocusLost
        // TODO add your handling code here:
        searchTxt.setText("Search something...");
    }//GEN-LAST:event_searchTxtFocusLost

    private void showPhoneDetail() {
        int rowCount = phoneTable.getSelectedRow();
        if (rowCount == -1) return;
        PhoneDTO phone = PhoneDAO.getPhone((String) model.getValueAt(rowCount, 0));
        distrivePhoneInfo(phone);
        ImageLoader.smartAttaching(phone.getPicture(), detailImg);
    }
    
    private void phoneTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneTableMouseClicked
        // TODO add your handling code here:
        showPhoneDetail();
    }//GEN-LAST:event_phoneTableMouseClicked
    
    private void phoneTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTableKeyReleased
        // TODO add your handling code here:
        showPhoneDetail();
    }//GEN-LAST:event_phoneTableKeyReleased

    private void searchTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ArrayList<PhoneDTO> list = PhoneDAO.findLikeName(searchTxt.getText());
            showPhones(list);
        }
    }//GEN-LAST:event_searchTxtKeyPressed
    
    PhoneDTO retrivePhoneInfo() {
        float price;
        try {
            price = Float.parseFloat(priceTxt.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid price format!");
            return null;
        }
        return new PhoneDTO(idTxt.getText(), nameTxt.getText(), osTxt.getText(), descriptionTxt.getText(), pictureLink, price);
    }
    
    void distrivePhoneInfo(PhoneDTO phone) {
        idTxt.setText(phone.getId());
        nameTxt.setText(phone.getName());
        osTxt.setText(phone.getOs());
        descriptionTxt.setText(phone.description);
        pictureLink = phone.picture;
        priceTxt.setText(String.format("%.2f", phone.getPrice()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JLabel detailImg;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField osTxt;
    private javax.swing.JTable phoneTable;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
